highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins:
  - jekyll-paginate
safe: true

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
production_path: https://kvokka.github.io
baseurl: /
title: Mike Belyakov's Resume
name: Mike Belyakov
email: kvokka@yahoo.com
email_full: mailto:kvokka@yahoo.com
github: kvokka
twitter: i_do_not_have_it
tel: +351 91 3079915
tel_full: tel:+351913079915
google_maps: 'https://goo.gl/maps/Uob4KxzvWeE2'
address:
  postcode: 4715 213
  city: Braga
  country: Portugal
google_analytics: UA-128594053-1

# needed for travis-ci build
exclude:
  - vendor
  - bin
